---
- name: Configure VPS
  hosts: CentOS7
  become: true
  gather_facts: false

  tasks:
    - name: Update yum cache
      yum:
        name: "*"
        state: latest

    - name: Install firewalld
      yum:
        name: firewalld
        state: present
    - name: Install firewalld and python-firewall packages
      yum:
        name:
          - firewalld
          - python-firewall
        state: present

    - name: Start firewalld service
      service:
        name: firewalld
        state: started
        enabled: yes

    - name: Configure firewalld to allow incoming connections from specific IP addresses
      firewalld:
        zone: trusted
        permanent: true
        state: enabled
        source: "{{ item }}"
        immediate: true
      loop:
        - 120.138.16.30
        - 120.138.23.30
        - 120.138.19.228
        - 122.62.200.10
    
    - name: Configure firewalld SSH
      firewalld:
        zone: public
        permanent: true
        state: disabled
        service: ssh

    - name: Reload firewalld
      service:
        name: firewalld
        state: reloaded

    - name: Install Docker dependencies
      yum:
        name:
          - yum-utils
          - device-mapper-persistent-data
          - lvm2
        state: present

    - name: Add Docker GPG key
      rpm_key:
        key: https://download.docker.com/linux/centos/gpg
        state: present

    - name: Add Docker repository
      yum_repository:
        name: docker-ce
        baseurl: https://download.docker.com/linux/centos/7/$basearch/stable
        gpgcheck: yes
        gpgkey: https://download.docker.com/linux/centos/gpg
        state: present

    - name: Install Docker
      yum:
        name: docker-ce
        state: present

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Install pip for Python 3
      yum:
        name: python3-pip
        state: present

    - name: Install required Python library
      pip:
        name: docker
        state: present
        executable: pip3

    - name: Install Rsync
      yum:
        name: rsync
        state: present

    - name: Copy application code
      synchronize:
        src: ./docker/
        dest: /app/
    
    - name: Delete previous Node.js app container
      docker_container:
        name: node-app
        image: nzarg/node-app
        state: absent
        restart_policy: always
        published_ports:
          - 80:80

    - name: Build docker container
      command: docker build -t nzarg/node-app .
      args:
        chdir: /app/

    - name: Run Node.js app container
      docker_container:
        name: node-app
        image: nzarg/node-app
        state: started
        restart_policy: always
        published_ports:
          - 80:80
