---
- name: Install Docker and Dependencies
  hosts: localhost
  become: true
  gather_facts: false

  tasks:
    - name: Install Docker dependencies
      apt:
        name:
          - update
          - python3
          - python3-pip
        state: present

    - name: Install required Python library (docker or docker-py)
      pip:
        name:
          - docker
          - docker-py
        state: present
        executable: pip3

    - name: Install Ansible
      pip:
        name: ansible
        state: present
        executable: pip3

    - name: Install Docker collections
      ansible-galaxy:
        name:
          - community.docker
          - ansible.posix
        state: present

    - name: Install rsync
      apt:
        name: rsync
        state: present

 